### **Assignment: Introduction to Linear Algebra and NumPy**

#### **Objective:**
This assignment will help you build a solid understanding of basic Linear Algebra concepts using Python and the NumPy library. You'll learn to create and manipulate arrays, perform mathematical operations, and explore properties and methods of arrays.


### **Working with NumPy**

NumPy is a powerful Python library for numerical computations, which allows easy manipulation of arrays and matrices.

**Task 1:** 
- Import the `numpy` library and check its version.


In [1]:
import numpy as np
print(np.__version__)

2.3.1



### **Creating a NumPy Array:**

NumPy arrays are a powerful way to store and process large datasets. In this section, you will learn to create arrays.

**Task 2:**
- Create a 1D NumPy array from a Python list of numbers: `[1, 2, 3, 4, 5]`.
- Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
- Generate an array of 10 evenly spaced values between 0 and 5.

In [18]:
a = np.array([1,2,3,4,5])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
c = np.linspace(0,5,10)
print(a)
print(b)
print(c)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### **Indexing and Slicing Arrays:**

Indexing and slicing allow you to access and modify specific elements of an array.

**Task 3:**
- Access the element in the second row, third column of the 2D array you created above.
- Slice the first two rows and the first two columns from the same array.
- Modify the value in the last row and first column to 100.


In [20]:
print(b[1,2])
print(b[0:2,0:2])
b[2,0] = 100
print(b)

6
[[1 2]
 [4 5]]
[[  1   2   3]
 [  4   5   6]
 [100   8   9]]


### **Properties and Methods of NumPy Arrays**

NumPy arrays have several useful properties and methods.

**Task 4:**
- Find the shape, size, and data type of the 2D array.
- Change the 1D array into a 2D array of shape (5,1).
- Flatten a multi-dimensional array back into a 1D array.

In [27]:
print(np.shape(b))
print(np.size(b))
print(b.dtype)

d = a.reshape(5,1)
print(d)

e = b.flatten()
print(e)

(3, 3)
9
int64
[[1]
 [2]
 [3]
 [4]
 [5]]
[  1   2   3   4   5   6 100   8   9]


### **Operations on NumPy Arrays**

Perform operations such as addition, subtraction, multiplication, and matrix multiplication on arrays.

**Task 5:**
- Add 5 to every element in the 1D array.
- Multiply the 2D array by 3.
- Perform matrix multiplication between the following two arrays:  
    ```python
    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

In [37]:
f = np.add(a,5)
print(f)

g = np.multiply(b,3)
print(g)

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C= A @ B
print(A)
print(B)
print(C)

[ 6  7  8  9 10]
[[  3   6   9]
 [ 12  15  18]
 [300  24  27]]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


### **Understanding Broadcasting**

Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.

**Task 6:**
- Create a 3x3 matrix of ones and a 1D array of length 3.
- Add the 1D array to each row of the matrix using broadcasting.

In [46]:
matrix = np.ones([3,3])
print(matrix)
vector = np.array([1,2,3])
print(vector)
matrix + vector

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1 2 3]


array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])