Array Methods`

In [1]:
import numpy as np

In [11]:
a = np.random.randint(10,50,size=(5,2,3), dtype="int64")

In [12]:
a.shape

(5, 2, 3)

In [13]:
a.ndim

3

In [14]:
a.dtype


dtype('int64')

In [15]:
a.size # numbe rof elements

30

In [16]:
a.T

array([[[35, 14, 37, 46, 25],
        [48, 13, 23, 27, 27]],

       [[15, 36, 44, 21, 28],
        [22, 39, 48, 46, 49]],

       [[18, 45, 10, 10, 47],
        [19, 13, 32, 38, 31]]])

In [17]:
a.shape

(5, 2, 3)

In [18]:
a.reshape(3,5,2)

array([[[35, 15],
        [18, 48],
        [22, 19],
        [14, 36],
        [45, 13]],

       [[39, 13],
        [37, 44],
        [10, 23],
        [48, 32],
        [46, 21]],

       [[10, 27],
        [46, 38],
        [25, 28],
        [47, 27],
        [49, 31]]])

In [19]:
a.reshape(-1,5,2)

array([[[35, 15],
        [18, 48],
        [22, 19],
        [14, 36],
        [45, 13]],

       [[39, 13],
        [37, 44],
        [10, 23],
        [48, 32],
        [46, 21]],

       [[10, 27],
        [46, 38],
        [25, 28],
        [47, 27],
        [49, 31]]])

In [22]:
a.ravel()

array([35, 15, 18, 48, 22, 19, 14, 36, 45, 13, 39, 13, 37, 44, 10, 23, 48,
       32, 46, 21, 10, 27, 46, 38, 25, 28, 47, 27, 49, 31])

In [23]:
a.flatten()

array([35, 15, 18, 48, 22, 19, 14, 36, 45, 13, 39, 13, 37, 44, 10, 23, 48,
       32, 46, 21, 10, 27, 46, 38, 25, 28, 47, 27, 49, 31])

In [40]:
b = np.random.randint(1,10,(2,3))
c = np.random.randint(1,10,(2,3))
print(b)
print(c)

[[9 2 4]
 [5 9 8]]
[[7 9 4]
 [7 1 8]]


In [43]:
d = np.concatenate([b,c], axis = 0)
d

array([[9, 2, 4],
       [5, 9, 8],
       [7, 9, 4],
       [7, 1, 8]], dtype=int32)

0 > column wise >vertical stack
1 > row wise > horizental stack

In [44]:
np.vstack((b,c))

array([[9, 2, 4],
       [5, 9, 8],
       [7, 9, 4],
       [7, 1, 8]], dtype=int32)

In [45]:
np.hstack((b,c))

array([[9, 2, 4, 7, 9, 4],
       [5, 9, 8, 7, 1, 8]], dtype=int32)

In [51]:
np.split(d,3, axis=1)

[array([[9],
        [5],
        [7],
        [7]], dtype=int32),
 array([[2],
        [9],
        [9],
        [1]], dtype=int32),
 array([[4],
        [8],
        [4],
        [8]], dtype=int32)]