Array Methods`

In [1]:
import numpy as np

In [11]:
a = np.random.randint(10,50,size=(5,2,3), dtype="int64")

In [12]:
a.shape

(5, 2, 3)

In [13]:
a.ndim

3

In [14]:
a.dtype


dtype('int64')

In [15]:
a.size # numbe rof elements

30

In [16]:
a.T

array([[[35, 14, 37, 46, 25],
        [48, 13, 23, 27, 27]],

       [[15, 36, 44, 21, 28],
        [22, 39, 48, 46, 49]],

       [[18, 45, 10, 10, 47],
        [19, 13, 32, 38, 31]]])

In [17]:
a.shape

(5, 2, 3)

In [18]:
a.reshape(3,5,2)

array([[[35, 15],
        [18, 48],
        [22, 19],
        [14, 36],
        [45, 13]],

       [[39, 13],
        [37, 44],
        [10, 23],
        [48, 32],
        [46, 21]],

       [[10, 27],
        [46, 38],
        [25, 28],
        [47, 27],
        [49, 31]]])

In [19]:
a.reshape(-1,5,2)

array([[[35, 15],
        [18, 48],
        [22, 19],
        [14, 36],
        [45, 13]],

       [[39, 13],
        [37, 44],
        [10, 23],
        [48, 32],
        [46, 21]],

       [[10, 27],
        [46, 38],
        [25, 28],
        [47, 27],
        [49, 31]]])

In [22]:
a.ravel()

array([35, 15, 18, 48, 22, 19, 14, 36, 45, 13, 39, 13, 37, 44, 10, 23, 48,
       32, 46, 21, 10, 27, 46, 38, 25, 28, 47, 27, 49, 31])

In [23]:
a.flatten()

array([35, 15, 18, 48, 22, 19, 14, 36, 45, 13, 39, 13, 37, 44, 10, 23, 48,
       32, 46, 21, 10, 27, 46, 38, 25, 28, 47, 27, 49, 31])

In [40]:
b = np.random.randint(1,10,(2,3))
c = np.random.randint(1,10,(2,3))
print(b)
print(c)

[[9 2 4]
 [5 9 8]]
[[7 9 4]
 [7 1 8]]


In [43]:
d = np.concatenate([b,c], axis = 0)
d

array([[9, 2, 4],
       [5, 9, 8],
       [7, 9, 4],
       [7, 1, 8]], dtype=int32)

0 > column wise >vertical stack
1 > row wise > horizental stack

In [44]:
np.vstack((b,c))

array([[9, 2, 4],
       [5, 9, 8],
       [7, 9, 4],
       [7, 1, 8]], dtype=int32)

In [45]:
np.hstack((b,c))

array([[9, 2, 4, 7, 9, 4],
       [5, 9, 8, 7, 1, 8]], dtype=int32)

In [51]:
np.split(d,3, axis=1)

[array([[9],
        [5],
        [7],
        [7]], dtype=int32),
 array([[2],
        [9],
        [9],
        [1]], dtype=int32),
 array([[4],
        [8],
        [4],
        [8]], dtype=int32)]

In [26]:
z = np.random.randint(2,20,(4,6))
z

array([[16, 14, 11, 17,  5,  6],
       [ 2, 10,  9, 19, 14,  6],
       [14,  9, 12,  2, 10, 10],
       [ 6,  7, 14,  3, 15, 14]], dtype=int32)

In [27]:
z.sum(axis = 0)

array([38, 40, 46, 41, 44, 36])

In [28]:
z.prod(axis = 0)

array([ 2688,  8820, 16632,  1938, 10500,  5040])

In [29]:
z.cumsum(axis = 0)

array([[16, 14, 11, 17,  5,  6],
       [18, 24, 20, 36, 19, 12],
       [32, 33, 32, 38, 29, 22],
       [38, 40, 46, 41, 44, 36]])

In [30]:
z.min(axis = 1)

array([5, 2, 2, 3], dtype=int32)

In [31]:
z.max(axis = 1)

array([17, 19, 14, 15], dtype=int32)

In [32]:
z.argmax(axis = 1)

array([3, 3, 0, 4])

In [33]:
z

array([[16, 14, 11, 17,  5,  6],
       [ 2, 10,  9, 19, 14,  6],
       [14,  9, 12,  2, 10, 10],
       [ 6,  7, 14,  3, 15, 14]], dtype=int32)

In [34]:
z.argmin(axis = 1)

array([4, 0, 3, 3])

In [36]:
z.clip(5,10)

array([[10, 10, 10, 10,  5,  6],
       [ 5, 10,  9, 10, 10,  6],
       [10,  9, 10,  5, 10, 10],
       [ 6,  7, 10,  5, 10, 10]], dtype=int32)