In [1]:
import numpy as np

In [14]:
a = np.array([[4,5,6],[5,7,9]])
b = np.array([[3,2,1],[9,8,1]])

In [15]:
a,b

(array([[4, 5, 6],
        [5, 7, 9]]),
 array([[3, 2, 1],
        [9, 8, 1]]))

## Arithmetic Operation

In [16]:
np.add(a,b)

array([[ 7,  7,  7],
       [14, 15, 10]])

In [17]:
np.subtract(a,b)

array([[ 1,  3,  5],
       [-4, -1,  8]])

In [18]:
np.multiply(a,b)

array([[12, 10,  6],
       [45, 56,  9]])

In [19]:
a ** 2

array([[16, 25, 36],
       [25, 49, 81]])

In [20]:
np.pow(a,5)

array([[ 1024,  3125,  7776],
       [ 3125, 16807, 59049]])

In [21]:
a % b

array([[1, 1, 0],
       [5, 7, 0]])

In [22]:
np.divmod(a,b)

(array([[1, 2, 6],
        [0, 0, 9]]),
 array([[1, 1, 0],
        [5, 7, 0]]))

In [23]:
np.ceil

array([[4, 5, 6],
       [5, 7, 9]])

In [25]:
np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974],
       [2.23606798, 2.64575131, 3.        ]])

## Trignometric

In [26]:
np.sin(a)

array([[-0.7568025 , -0.95892427, -0.2794155 ],
       [-0.95892427,  0.6569866 ,  0.41211849]])

In [28]:
new = 1/ np.tan(a)
new

array([[ 0.86369115, -0.29581292, -3.436353  ],
       [-0.29581292,  1.14751542, -2.21084541]])

## Rounding Operation

In [30]:
np.round(new, decimals=3)

array([[ 0.864, -0.296, -3.436],
       [-0.296,  1.148, -2.211]])

In [31]:
np.fix(new)

array([[ 0., -0., -3.],
       [-0.,  1., -2.]])

In [32]:
np.ceil(new)

array([[ 1., -0., -3.],
       [-0.,  2., -2.]])

## Matrix Operation

In [22]:
a = np.array([[4,5,6],[1,2,3]])
b = np.random.randint(0,10, (3,3))

In [23]:
a

array([[4, 5, 6],
       [1, 2, 3]])

In [24]:
b

array([[3, 9, 5],
       [4, 9, 6],
       [6, 5, 5]], dtype=int32)

In [25]:
np.dot(a,b)

array([[ 68, 111,  80],
       [ 29,  42,  32]])

In [26]:
np.dot(b,a)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [27]:
#a.T
np.transpose(a)

array([[4, 1],
       [5, 2],
       [6, 3]])

In [28]:
np.trace(b)

np.int64(17)

## Inverse operation

In [31]:
np.linalg.inv(b)

array([[ 0.78947368, -1.05263158,  0.47368421],
       [ 0.84210526, -0.78947368,  0.10526316],
       [-1.78947368,  2.05263158, -0.47368421]])

In [32]:
np.dot(
    b, np.linalg.inv(b)
).round()

array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])

solve equation x + 2y =1, 3x + 5y = 2 

In [39]:
a = np.array([[1,2],[3,5]])
b = np.array([1,2])

In [40]:
x = np.linalg.solve(a,b)

In [41]:
x

array([-1.,  1.])

## Array Broadcasting

In [42]:
a * 4

array([[ 4,  8],
       [12, 20]])