In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ------------ --------------------------- 3.9/12.7 MB 24.8 MB/s eta 0:00:01
   --------------------- ------------------ 6.8/12.7 MB 19.0 MB/s eta 0:00:01
   -------------------------------------- - 12.3/12.7 MB 21.7 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 21.1 MB/s eta 0:00:00


In [1]:
import numpy as np

In [5]:
np.__version__

'2.3.1'

Creating Numpy Array

In [21]:
list1 = [[2,3,4]]

In [22]:
arr1 = np.array(list1)

In [23]:
arr1

array([[2, 3, 4]])

In [24]:
arr1.shape

(1, 3)

In [25]:
arr1.ndim

2

In [27]:
list2 = [[1,2,3],
         [4,5,6],
         [7,8,9]]

arr2 =np.array(list2)

In [28]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr2.shape

(3, 3)

In [30]:
arr2.ndim

2

In [33]:
np.zeros(shape=(4,4), dtype= int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [39]:
np.ones(shape=(2,6,6), dtype= "int64")

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

In [44]:
np.full(shape=(3,4), fill_value=6.7)

array([[6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7],
       [6.7, 6.7, 6.7, 6.7]])

In [45]:
np.arange(1,90,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86])

In [49]:
np.linspace((0,1,2),(10,20,30),num=20)

array([[ 0.        ,  1.        ,  2.        ],
       [ 0.52631579,  2.        ,  3.47368421],
       [ 1.05263158,  3.        ,  4.94736842],
       [ 1.57894737,  4.        ,  6.42105263],
       [ 2.10526316,  5.        ,  7.89473684],
       [ 2.63157895,  6.        ,  9.36842105],
       [ 3.15789474,  7.        , 10.84210526],
       [ 3.68421053,  8.        , 12.31578947],
       [ 4.21052632,  9.        , 13.78947368],
       [ 4.73684211, 10.        , 15.26315789],
       [ 5.26315789, 11.        , 16.73684211],
       [ 5.78947368, 12.        , 18.21052632],
       [ 6.31578947, 13.        , 19.68421053],
       [ 6.84210526, 14.        , 21.15789474],
       [ 7.36842105, 15.        , 22.63157895],
       [ 7.89473684, 16.        , 24.10526316],
       [ 8.42105263, 17.        , 25.57894737],
       [ 8.94736842, 18.        , 27.05263158],
       [ 9.47368421, 19.        , 28.52631579],
       [10.        , 20.        , 30.        ]])

In [51]:
np.random.randint(1,10, size=(2,2))

array([[1, 4],
       [2, 9]], dtype=int32)

In [2]:
np.ones(shape = (2, 2, 1, 3), dtype="int8")

array([[[[1, 1, 1]],

        [[1, 1, 1]]],


       [[[1, 1, 1]],

        [[1, 1, 1]]]], dtype=int8)

Accessing an Array

In [4]:
a = np.array([1,2,3,4,5])

In [5]:
a[4]

np.int64(5)

In [6]:
a[0:4:2]

array([1, 3])

In [10]:
#2D
b = np.random.randint(0,25, size=(3,3))

In [11]:
b

array([[19, 21,  5],
       [20,  5,  8],
       [24, 18,  6]], dtype=int32)

In [12]:
b[1,1]

np.int32(5)

In [14]:
b[-1,0]

np.int32(24)

In [15]:
#slicing 2d array
b[1:3,:2]

array([[20,  5],
       [24, 18]], dtype=int32)

In [17]:
b[:,2][1]

np.int32(8)

In [25]:
#2D
c = np.random.randint(0,25, size=(3,3,2))

In [26]:
c

array([[[ 8,  0],
        [18,  1],
        [ 5,  9]],

       [[ 4,  7],
        [23,  9],
        [ 1,  4]],

       [[14,  3],
        [10,  0],
        [ 9,  6]]], dtype=int32)

In [22]:
c[0,2,1]

np.int32(0)

In [27]:
c[:,2,:]

array([[5, 9],
       [1, 4],
       [9, 6]], dtype=int32)

In [30]:
dataset = np.random.randint(0,100,(1600,25))

In [31]:
dataset.shape

(1600, 25)

In [32]:
image_dataset = np.random.randint(0,100,(16,3,720,720))

In [34]:
image_dataset[1,0,:,:]

array([[52, 97, 60, ..., 45,  3, 50],
       [51, 93, 33, ..., 26, 15, 28],
       [34, 90, 68, ..., 30, 65, 27],
       ...,
       [61, 18, 71, ..., 27, 12,  8],
       [ 7, 42, 54, ..., 69, 26, 81],
       [43, 54, 73, ..., 11, 89, 16]], shape=(720, 720), dtype=int32)

Boolean or Mask Indexing

In [35]:
a = np.random.randint(1,10,(5,5))

In [36]:
mask = a>5

In [37]:
mask

array([[False,  True, False,  True, False],
       [False, False, False, False, False],
       [ True, False, False, False,  True],
       [False, False, False, False, False],
       [False, False,  True, False, False]])

In [38]:
a[mask]

array([6, 6, 6, 6, 6], dtype=int32)

In [39]:
mask = [True, False, False, True, True]

In [42]:
a[:,mask]

array([[1, 6, 5],
       [4, 2, 1],
       [6, 4, 6],
       [2, 2, 2],
       [4, 5, 5]], dtype=int32)

In [43]:
a

array([[1, 6, 3, 6, 5],
       [4, 5, 4, 2, 1],
       [6, 2, 4, 4, 6],
       [2, 3, 4, 2, 2],
       [4, 3, 6, 5, 5]], dtype=int32)